// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPPostFromVideoConsole.Context;

#nullable disable

namespace WPPostFromVideoConsole.Migrations
{
    [DbContext(typeof(VideoContext))]
    [Migration("20221021180834_posts7")]
    partial class posts7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("WPPostFromVideoConsole.Models.PostParams", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoIdx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("postName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("VideoIdx");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WPPostFromVideoConsole.Models.Video", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idx");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("WPPostFromVideoConsole.Models.PostParams", b =>
                {
                    b.HasOne("WPPostFromVideoConsole.Models.Video", "Video")
                        .WithMany("PostParams")
                        .HasForeignKey("VideoIdx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("WPPostFromVideoConsole.Models.Video", b =>
                {
                    b.Navigation("PostParams");
                });
#pragma warning restore 612, 618
        }
    }
}
